version: "3.9"
services:
  channels-dvr: # Should be exact same name as "id" field in config.json
    container_name: channels-dvr # Should be exact same name as "id" field in config.json
    image: fancybits/channels-dvr:latest # Try to avoid "latest" tag. As it may break configs in the future.
    restart: unless-stopped # Do not change this
    environment:
      - TZ=${TZ} # Can use any env variable. See "environment variables" section in the docs
    volumes:
      - ${APP_DATA_DIR}/data/config:/channels-dvr
      - ${APP_DATA_DIR}/data/recordings:/shares/DVR
    ports:
      - ${APP_PORT}:8089
    devices:
      - /dev/dri:/dev/dri
    networks:
      - tipi_main_network # That should not be changed
    labels: # Use your editors search and replace feature to replace all instances of "channels-dvr" with your app name in the traefik labels
      # Main
      traefik.enable: true
      traefik.http.middlewares.channels-dvr-web-redirect.redirectscheme.scheme: https
      traefik.http.services.channels-dvr.loadbalancer.server.port: 8089 # Should be the same as the app internal port so for this example 9443
      # Web
      traefik.http.routers.channels-dvr-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.channels-dvr-insecure.entrypoints: web
      traefik.http.routers.channels-dvr-insecure.service: channels-dvr
      traefik.http.routers.channels-dvr-insecure.middlewares: channels-dvr-web-redirect
      # Websecure
      traefik.http.routers.channels-dvr.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.channels-dvr.entrypoints: websecure
      traefik.http.routers.channels-dvr.service: channels-dvr
      traefik.http.routers.channels-dvr.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.channels-dvr-local-insecure.rule: Host(`channels-dvr.${LOCAL_DOMAIN}`)
      traefik.http.routers.channels-dvr-local-insecure.entrypoints: web
      traefik.http.routers.channels-dvr-local-insecure.service: channels-dvr
      traefik.http.routers.channels-dvr-local-insecure.middlewares: channels-dvr-web-redirect
      # Local domain secure
      traefik.http.routers.channels-dvr-local.rule: Host(`channels-dvr.${LOCAL_DOMAIN}`)
      traefik.http.routers.channels-dvr-local.entrypoints: websecure
      traefik.http.routers.channels-dvr-local.service: channels-dvr
      traefik.http.routers.channels-dvr-local.tls: true
